### ISSUE TITLE
Information Dump

### ISSUE THREAD

**Issue by eternalleigh** [drapergeek/findit#47]
Is there a quick way to get all of the computers, laptops, and ipads off this? We are running another (wcpss) inventory system. I still need projectors, smartboards, etc... just not computers, laptops or ipads.

**Comment by drapergeek** [comment]
>Is there a quick way to get all of the computers, laptops, and ipads off this?

When you say "get it off", do you mean delete? Or do you mean you want an excel list or something?

**Comment by eternalleigh** [comment]
I mean delete. I can export it with your handy dandy button :)

**Comment by drapergeek** [comment]
>["Printer", "Laptop", "Desktop", "Projector", "Mobile", "Interactive Board", "Document Camera", "Other"]

Those are the "Types" of items you have. What types do you want deleted? I just want to be sure before I run this query, no going back.

**Comment by eternalleigh** [comment]
Let's take out desktops and laptops, I may do mobiles later but I dont want to go through and check right now.

**Comment by drapergeek** [comment]
Desktops and laptops are gone.
